# Generated by Django 2.1.5 on 2019-02-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blog', '0004_auto_20190215_1721'),
        ('users', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
